listener {
    	timeout = 110
	on-timeout = notify-send "System Idle, locking in 10sec"
}

listener {
	timeout = 180
	on-timeout = fish ~/.local/bin/monitors_stanby.fish 02
	on-resume = fish ~/.local/bin/monitors_stanby.fish 01 & ~/.local/bin/rlwpp
}

listener {
    	timeout = 600
    	on-timeout = systemctl suspend
	on-resume = fish ~/.local/bin/monitors_stanby.fish 01
}
